"""initial_schema_creation

Revision ID: 3ddc33d673e0
Revises: 
Create Date: 2026-03-25 08:06:30.850840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddc33d673e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'context',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'general'"))
    op.drop_index(op.f('idx_files_context'), table_name='files')
    op.drop_index(op.f('idx_files_course_id'), table_name='files')
    op.drop_index(op.f('idx_files_module_id'), table_name='files')
    op.drop_index(op.f('idx_files_topic_id'), table_name='files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_files_topic_id'), 'files', ['topic_id'], unique=False)
    op.create_index(op.f('idx_files_module_id'), 'files', ['module_id'], unique=False)
    op.create_index(op.f('idx_files_course_id'), 'files', ['course_id'], unique=False)
    op.create_index(op.f('idx_files_context'), 'files', ['context'], unique=False)
    op.alter_column('files', 'context',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'general'"))
    # ### end Alembic commands ###